import type { PoetGraph } from '../types'

export const fixtureGraph: PoetGraph = {
  poets: [
    {
      depth: 0.92,
      dynasty: '唐',
      fame: 0.99,
      id: '李白',
      name: '李白',
      notableWork: '将进酒',
      position: { x: 0.35, y: 0.11 },
      spotlight: '李白与盛唐诗友形成了最醒目的连接。',
      tags: ['浪漫主义', '游侠气', '盛唐'],
    },
    {
      depth: 0.64,
      dynasty: '唐',
      fame: 0.6,
      id: '孟浩然',
      name: '孟浩然',
      notableWork: '春晓',
      position: { x: 0.3, y: 0.32 },
      spotlight: '孟浩然和李白互为高亮节点。',
      tags: ['山水田园', '高士气'],
    },
    {
      depth: 0.74,
      dynasty: '唐',
      fame: 0.92,
      id: '杜甫',
      name: '杜甫',
      notableWork: '春望',
      position: { x: 0.12, y: -0.08 },
      spotlight: '杜甫在网络里保持强关联。',
      tags: ['现实主义', '盛唐'],
    },
    {
      depth: 0.58,
      dynasty: '唐',
      fame: 0.55,
      id: '王昌龄',
      name: '王昌龄',
      notableWork: '出塞',
      position: { x: -0.16, y: 0.18 },
      spotlight: '王昌龄与李白存在送别回响。',
      tags: ['边塞诗', '七绝'],
    },
    {
      depth: 0.69,
      dynasty: '唐',
      fame: 0.81,
      id: '白居易',
      name: '白居易',
      notableWork: '长恨歌',
      position: { x: -0.12, y: 0.37 },
      spotlight: '白居易与元稹构成元白中轴。',
      tags: ['元白', '新乐府'],
    },
    {
      depth: 0.68,
      dynasty: '唐',
      fame: 0.6,
      id: '元稹',
      name: '元稹',
      notableWork: '离思五首',
      position: { x: -0.22, y: 0.28 },
      spotlight: '元稹与白居易构成元白双核。',
      tags: ['元白', '酬答'],
    },
    {
      depth: 0.42,
      dynasty: '唐',
      fame: 0.18,
      id: '裴迪',
      name: '裴迪',
      notableWork: '辋川集',
      position: { x: 0.42, y: -0.24 },
      spotlight: '裴迪位于边缘低频节点。',
      tags: ['山水', '隐逸'],
    },
  ],
  relations: [
    {
      excerpt: '吾爱孟夫子，风流天下闻',
      id: 'r1',
      intensity: 0.94,
      note: '李白在赠诗中直接写给孟浩然。',
      poemTitle: '赠孟浩然',
      source: '李白',
      target: '孟浩然',
      type: 'gift',
      typeLabel: '赠诗',
    },
    {
      excerpt: '白也诗无敌，飘然思不群',
      id: 'r2',
      intensity: 0.86,
      note: '杜甫在诗中提及李白。',
      poemTitle: '春日忆李白',
      source: '杜甫',
      target: '李白',
      type: 'mention',
      typeLabel: '提及',
    },
    {
      excerpt: '我寄愁心与明月，随君直到夜郎西',
      id: 'r3',
      intensity: 0.82,
      note: '李白将情绪投向王昌龄。',
      poemTitle: '闻王昌龄左迁龙标遥有此寄',
      source: '李白',
      target: '王昌龄',
      type: 'gift',
      typeLabel: '赠诗',
    },
    {
      excerpt: '频梦君来不我思，梦君时我失欢词',
      id: 'r4',
      intensity: 0.97,
      note: '白居易主动回应元稹。',
      poemTitle: '酬乐天频梦微之',
      source: '白居易',
      target: '元稹',
      type: 'gift',
      typeLabel: '赠诗',
    },
    {
      excerpt: '晨起临风一惆怅，通川湓水断相闻',
      id: 'r5',
      intensity: 0.89,
      note: '元稹梦中忆及白居易。',
      poemTitle: '梦微之',
      source: '元稹',
      target: '白居易',
      type: 'mention',
      typeLabel: '提及',
    },
  ],
}
